using System;
using System.Linq;
using Konduit.SourceGeneration.Model;

namespace Konduit.SourceGeneration.Emitting;

/// <summary>Writes the proxy class for one service interface.</summary>
internal static class ProxyEmitter
{
    public static string Emit(ProxySpec spec)
    {
        var source = new SourceBuilder();

        source
            .Line("// <auto-generated/>")
            .Line("#nullable enable")
            .Line("#pragma warning disable CS0169, CS0414, CS1591, CS8600, CS8601, CS8602, CS8603, CS8604, CS8619")
            .Line()
            .Open($"namespace {Names.Namespace}")
            .Open($"internal sealed class {spec.ProxyTypeName} : {spec.InterfaceFullyQualified}, {Names.Proxy}");

        EmitFields(source, spec);

        foreach (var method in spec.Methods)
        {
            source.Line();
            EmitMethod(source, spec, method);
        }

        foreach (var property in spec.Properties)
        {
            source.Line();
            EmitProperty(source, property);
        }

        foreach (var @event in spec.Events)
        {
            source.Line();
            EmitEvent(source, @event);
        }

        return source.Close().Close().ToString();
    }

    private static void EmitFields(SourceBuilder source, ProxySpec spec) =>
        source
            .Line($"private readonly {spec.InterfaceFullyQualified} _target;")
            .Line($"private readonly {Names.Delegate} _pipeline;")
            .Line($"private readonly {Names.ServiceProvider} _services;")
            .Line()
            .Open($"public {spec.ProxyTypeName}({spec.InterfaceFullyQualified} target, {Names.Delegate} pipeline, {Names.ServiceProvider} services)")
            .Line("_target = target;")
            .Line("_pipeline = pipeline;")
            .Line("_services = services;")
            .Close()
            .Line()
            .Line("public object KonduitTarget => _target;");

    private static void EmitMethod(SourceBuilder source, ProxySpec spec, MethodSpec method)
    {
        if (method.PassThrough)
        {
            EmitPassThrough(source, method);
            return;
        }

        if (method.IsGeneric)
        {
            EmitGenericStatics(source, spec, method);
        }
        else
        {
            EmitStatics(source, spec, method, "private static readonly", MethodField(method), TerminalField(method));
        }

        source.Line();
        source.Line(Signature(method));
        EmitConstraints(source, method);
        source.OpenBlock();
        EmitBody(source, method);
        source.Close();
    }

    private static void EmitPassThrough(SourceBuilder source, MethodSpec method)
    {
        var call = $"_target.{method.Name}{TypeArguments(method)}({CallArguments(method)})";
        var body = $"=> {(method.ReturnModifier.Length > 0 ? "ref " : string.Empty)}{call};";

        source.Line(Signature(method));
        EmitConstraints(source, method);
        source.Line("    " + body);
    }

    private static void EmitGenericStatics(SourceBuilder source, ProxySpec spec, MethodSpec method)
    {
        source.Line($"private static class __statics_{method.MemberId}<{string.Join(", ", method.TypeParameters)}>");
        EmitConstraints(source, method);
        source.OpenBlock();
        EmitStatics(source, spec, method, "internal static readonly", "Method", "Terminal");
        source.Close();
    }

    private static void EmitStatics(
        SourceBuilder source,
        ProxySpec spec,
        MethodSpec method,
        string modifiers,
        string methodField,
        string terminalField)
    {
        var parameters = method.Parameters.Count == 0
            ? $"global::System.Array.Empty<{Names.Parameter}>()"
            : "new " + Names.Parameter + "[] { " + string.Join(
                ", ",
                method.Parameters.Select((p, i) => $"new {Names.Parameter}(\"{p.Name}\", typeof({p.TypeForTypeOf}), {i})")) + " }";

        source
            .Line($"{modifiers} {Names.Method} {methodField} = new {Names.Method}(")
            .Line($"    typeof({spec.InterfaceForTypeOf}),")
            .Line($"    \"{method.Name}\",")
            .Line($"    typeof({method.ReturnTypeForTypeOf}),")
            .Line($"    {parameters});")
            .Line();

        EmitTerminal(source, spec, method, modifiers, terminalField);
    }

    private static void EmitTerminal(
        SourceBuilder source,
        ProxySpec spec,
        MethodSpec method,
        string modifiers,
        string field)
    {
        var call = $"(({spec.InterfaceFullyQualified})context.Target).{method.Name}{TypeArguments(method)}({TerminalArguments(method)})";

        source.Open($"{modifiers} {Names.Delegate} {field} = static {(method.IsAsync ? "async " : string.Empty)}context =>");

        switch (method.Kind)
        {
            case ReturnKind.Void:
                source.Line($"{call};").Line("return default;");
                break;

            case ReturnKind.Value:
                source.Line($"context.Result = {call};").Line("return default;");
                break;

            case ReturnKind.AwaitableVoid:
                source.Line($"await {call}.ConfigureAwait(false);");
                break;

            case ReturnKind.AwaitableValue:
                source.Line($"context.Result = await {call}.ConfigureAwait(false);");
                break;
        }

        source.Close(";");
    }

    private static void EmitBody(SourceBuilder source, MethodSpec method)
    {
        var prefix = method.IsGeneric
            ? $"__statics_{method.MemberId}<{string.Join(", ", method.TypeParameters)}>."
            : string.Empty;

        var methodField = method.IsGeneric ? prefix + "Method" : MethodField(method);
        var terminalField = method.IsGeneric ? prefix + "Terminal" : TerminalField(method);

        var arguments = method.Parameters.Count == 0
            ? "global::System.Array.Empty<object?>()"
            : "new object?[] { " + string.Join(", ", method.Parameters.Select(p => p.Name)) + " }";

        var cancellation = method.Parameters.FirstOrDefault(p => p.IsCancellationToken);
        var initializer = cancellation is null ? string.Empty : $" {{ CancellationToken = {cancellation.Name} }}";

        source.Line($"var context = new {Names.Context}(_target, {methodField}, {arguments}, _services, {terminalField}){initializer};");

        switch (method.Kind)
        {
            case ReturnKind.Void:
                source.Line($"{Names.Sync}.Wait(_pipeline(context));");
                break;

            case ReturnKind.Value:
                source
                    .Line($"{Names.Sync}.Wait(_pipeline(context));")
                    .Line($"return ({method.ReturnTypeFullyQualified})context.Result!;");
                break;

            case ReturnKind.AwaitableVoid:
                source.Line("await _pipeline(context).ConfigureAwait(false);");
                break;

            case ReturnKind.AwaitableValue:
                source
                    .Line("await _pipeline(context).ConfigureAwait(false);")
                    .Line($"return ({method.AwaitedTypeFullyQualified})context.Result!;");
                break;
        }
    }

    private static void EmitProperty(SourceBuilder source, PropertySpec property)
    {
        var access = property.IsIndexer
            ? $"_target[{string.Join(", ", property.Parameters.Select(p => p.Name))}]"
            : $"_target.{property.Name}";

        var declaration = property.IsIndexer
            ? $"public {property.TypeFullyQualified} this[{string.Join(", ", property.Parameters.Select(p => $"{p.Modifier}{p.TypeFullyQualified} {p.Name}"))}]"
            : $"public {property.TypeFullyQualified} {property.Name}";

        source.Open(declaration);

        if (property.HasGetter)
        {
            source.Line($"get => {access};");
        }

        // An init-only member can only be assigned on `this` during construction, so a proxy has no
        // way to forward one to the implementation it already wraps.
        if (property.SetterKeyword == "init")
        {
            source.Line($"init => throw new global::System.NotSupportedException(\"Konduit cannot forward the init-only property '{property.Name}' to the wrapped implementation.\");");
        }
        else if (property.SetterKeyword is not null)
        {
            source.Line($"set => {access} = value;");
        }

        source.Close();
    }

    private static void EmitEvent(SourceBuilder source, EventSpec @event) =>
        source
            .Open($"public event {@event.TypeFullyQualified} {@event.Name}")
            .Line($"add => _target.{@event.Name} += value;")
            .Line($"remove => _target.{@event.Name} -= value;")
            .Close();

    private static void EmitConstraints(SourceBuilder source, MethodSpec method)
    {
        foreach (var constraint in method.ConstraintClauses)
        {
            source.Line("    " + constraint);
        }
    }

    private static string Signature(MethodSpec method)
    {
        var parameters = string.Join(", ", method.Parameters.Select(p => $"{p.Modifier}{p.TypeFullyQualified} {p.Name}"));

        return $"public {(method.IsAsync ? "async " : string.Empty)}{method.ReturnModifier}"
            + $"{method.ReturnTypeFullyQualified} {method.Name}{TypeArguments(method)}({parameters})";
    }

    private static string MethodField(MethodSpec method) => $"__method_{method.MemberId}";

    private static string TerminalField(MethodSpec method) => $"__terminal_{method.MemberId}";

    private static string TypeArguments(MethodSpec method) =>
        method.IsGeneric ? $"<{string.Join(", ", method.TypeParameters)}>" : string.Empty;

    private static string CallArguments(MethodSpec method) =>
        string.Join(", ", method.Parameters.Select(p => $"{p.Modifier}{p.Name}"));

    private static string TerminalArguments(MethodSpec method) =>
        string.Join(", ", method.Parameters.Select((p, i) => $"({p.TypeFullyQualified})context.Arguments[{i}]!"));
}
