using System.Collections.Generic;
using Konduit.SourceGeneration.Model;

namespace Konduit.SourceGeneration.Emitting;

/// <summary>
/// Writes the module initializer that publishes every generated proxy to the runtime registry.
/// </summary>
/// <remarks>
/// A module initializer runs before any other code in the assembly, so the registry is populated by
/// the time the composition root calls <c>WithMiddleware&lt;T&gt;()</c> and can fail fast when it is not.
/// </remarks>
internal static class RegistrationsEmitter
{
    public static string Emit(IReadOnlyList<ProxySpec> specs, bool needsAttributePolyfill)
    {
        var source = new SourceBuilder()
            .Line("// <auto-generated/>")
            .Line("#nullable enable")
            .Line();

        if (needsAttributePolyfill)
        {
            source
                .Open("namespace System.Runtime.CompilerServices")
                .Line("[global::System.AttributeUsage(global::System.AttributeTargets.Method, Inherited = false)]")
                .Line("internal sealed class ModuleInitializerAttribute : global::System.Attribute { }")
                .Close()
                .Line();
        }

        source
            .Open($"namespace {Names.Namespace}")
            .Open("internal static class KonduitProxyRegistrations")
            .Line($"[{Names.ModuleInitializer}]")
            .Open("internal static void Initialize()");

        foreach (var spec in specs)
        {
            source.Line($"{Names.Registry}.Register(");
            source.Line($"    typeof({spec.InterfaceForTypeOf}),");

            // A specialised proxy is registered against the implementation as well, so the right one
            // is chosen for the instance actually being wrapped.
            if (spec.ImplementationForTypeOf is { } implementation)
            {
                source.Line($"    typeof({implementation}),");
            }

            source.Line($"    static (target, pipeline, services) => new {spec.ProxyTypeName}(({spec.InterfaceFullyQualified})target, pipeline, services));");
        }

        return source.Close().Close().Close().ToString();
    }
}
